language: java
jdk:
- oraclejdk8
cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"
deploy:
  provider: releases
  api_key:
    secure: OIXjanzuR8+efwRgaILw3g3W5O8wYcGwcedvUakVOiObq/RLAAF67lubsxkRIZRnv8ag+oIzwGMW2Fo3EPu56j15+KO1lhzSeIRHLZCzSMD3dpa75se/W7ph3rUbssPwAHkHSQOduxTP14xUKw15sC2IlZpjT9tWsGLBTde1rVFpyiu/zqYHgIo3FiWTVEdWYWjZtzW8aoAo/D29oaSlyY2bOawE8SpvGil50BG9DM24OdZPPfE9jx+1y+sSzLzjjGL6JlD5Wvn0AJI3NkpN/3T0VVV6RRWCaYL05khAwa2qBUT8Fp0uR4fVFRLdsRG4pKNK5FfwLd+CTArwjqm5qlOqrklfzh7IwJge8rtDYIrjp5ADFwJ8b5XNlBaSphTJWL1+qhBzFNJ70BN/QwX/4bxGBx55h18cl0eQ4eOYae7uiCHe39xluA+TC2G2N3Edv2pPzFQyPdOdsBxsjrcMj9gHK4SzoGAY0HiPfEeGm4ZjdLtCg1pUvGc2I8zdytYRosFOMsB1BJdYW9o10i/RHsoTtyLKFcQ3eJXWd5rDc/IUqDgtoixVPQlKkXyPR6GW+ILdP/W7GxbN7ZPenLt6T3EIln9SQTa2z73Y7eQpNiAeCQTv4QscE5ijXXkFRXqxgkgFfuafykfiopxqxeJKLdRh3uT9tXTCyw2z51UCYs0=
  file: web/build/libs/Cryptotrader.jar
  on:
    repo: Cryptopurse/Cryptotrader
    tags: true