spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://mysql:3306/cryptopurse
    username: cryptopurse
    password: mQKmCt1DdKon93Rz2CGqmPFPairmNrOjZZEbdQ1qM9ZqC7Hd5z
    max-active: 10
    max-idle: 5
    min-idle: 2
    initial-size: 5
    remove-abandoned: true
    driver-class-name: com.mysql.jdbc.Driver

com:
  cryptopurse:
    mail:
      domain: sandbox871877c7759d4848a400984def71bc05.mailgun.org
      apikey: key-510847558185974ea3ba84ba7bfd79b9
      sender: postmaster@sandbox871877c7759d4848a400984def71bc05.mailgun.org
    fullbaseurl: https://test.cryptopurse.io

debug: true

eureka:
  client:
    service-url:
      defaultZone: http://cryptopurse-discovery:8761/eureka/

