spring:
  datasource:
    max-active: 10
    max-idle: 5
    min-idle: 2
    initial-size: 5
    remove-abandoned: true
    test-on-borrow: true
    test-on-connect: true
    validation-query: SELECT 1
  application:
    name: Cryptotrader
  thymeleaf:
    cache: true
    mode: HTML5
  jpa:
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  profiles:
    active: local
server:
  port: 8080
  display-name: CryptoTrader
  error:
    whitelabel:
      enabled: false

management:
  security:
    enabled: true
    role: ADMIN

hibernate:
  format_sql: false
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  show_sql: false
  hbm2ddl:
    auto: none

com:
  cryptopurse:
    fullbaseurl: http://localhost:8080
    cryptotrader:
      messaging:
        ws:
          stomp-endpoint: /ws
          app-endpoint: /app
          heartbeatMillis: 5000
          disconnectDelayMillis: 10000

      watch:
        exchange: KRAKEN
        currencypair: ETH_EUR


# Logging Configuration
logging:
  file: cryptotrading.log
  path: /var/log/cryptotrading
  level: info


# actuator
endpoints:
  actuator:
    enabled: true
    sensitive: false
  metrics:
    sensitive: false
