spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/cryptotrading
    username: cryptotrading
    password: cryptotrading
    driver-class-name: com.mysql.jdbc.Driver


com:
  karmahostage:
    cryptotrader:
      mail:
        domain: sandbox871877c7759d4848a400984def71bc05.mailgun.org
        apikey: key-510847558185974ea3ba84ba7bfd79b9
        sender: postmaster@sandbox871877c7759d4848a400984def71bc05.mailgun.org

debug: true